// Generated by gencpp from file robot2/Pose2DOrient.msg
// DO NOT EDIT!


#ifndef ROBOT2_MESSAGE_POSE2DORIENT_H
#define ROBOT2_MESSAGE_POSE2DORIENT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot2
{
template <class ContainerAllocator>
struct Pose2DOrient_
{
  typedef Pose2DOrient_<ContainerAllocator> Type;

  Pose2DOrient_()
    : x(0)
    , y(0)
    , theta(0)  {
    }
  Pose2DOrient_(const ContainerAllocator& _alloc)
    : x(0)
    , y(0)
    , theta(0)  {
  (void)_alloc;
    }



   typedef int32_t _x_type;
  _x_type x;

   typedef int32_t _y_type;
  _y_type y;

   typedef int32_t _theta_type;
  _theta_type theta;





  typedef boost::shared_ptr< ::robot2::Pose2DOrient_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot2::Pose2DOrient_<ContainerAllocator> const> ConstPtr;

}; // struct Pose2DOrient_

typedef ::robot2::Pose2DOrient_<std::allocator<void> > Pose2DOrient;

typedef boost::shared_ptr< ::robot2::Pose2DOrient > Pose2DOrientPtr;
typedef boost::shared_ptr< ::robot2::Pose2DOrient const> Pose2DOrientConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot2::Pose2DOrient_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot2::Pose2DOrient_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robot2

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'robot2': ['/home/florian/catkin_workspace/src/robot2/msg', '/home/florian/catkin_workspace/src/robot2/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robot2::Pose2DOrient_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot2::Pose2DOrient_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot2::Pose2DOrient_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot2::Pose2DOrient_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot2::Pose2DOrient_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot2::Pose2DOrient_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot2::Pose2DOrient_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2bff1127cd10ca02349c9c72c72be56e";
  }

  static const char* value(const ::robot2::Pose2DOrient_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2bff1127cd10ca02ULL;
  static const uint64_t static_value2 = 0x349c9c72c72be56eULL;
};

template<class ContainerAllocator>
struct DataType< ::robot2::Pose2DOrient_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot2/Pose2DOrient";
  }

  static const char* value(const ::robot2::Pose2DOrient_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot2::Pose2DOrient_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 x\n\
int32 y\n\
int32 theta\n\
";
  }

  static const char* value(const ::robot2::Pose2DOrient_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot2::Pose2DOrient_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.theta);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Pose2DOrient_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot2::Pose2DOrient_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot2::Pose2DOrient_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<int32_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<int32_t>::stream(s, indent + "  ", v.y);
    s << indent << "theta: ";
    Printer<int32_t>::stream(s, indent + "  ", v.theta);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT2_MESSAGE_POSE2DORIENT_H
