// Generated by gencpp from file robot2/Reperage.msg
// DO NOT EDIT!


#ifndef ROBOT2_MESSAGE_REPERAGE_H
#define ROBOT2_MESSAGE_REPERAGE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot2
{
template <class ContainerAllocator>
struct Reperage_
{
  typedef Reperage_<ContainerAllocator> Type;

  Reperage_()
    : alpha(0.0)
    , omega(0.0)
    , gamma(0.0)  {
    }
  Reperage_(const ContainerAllocator& _alloc)
    : alpha(0.0)
    , omega(0.0)
    , gamma(0.0)  {
  (void)_alloc;
    }



   typedef float _alpha_type;
  _alpha_type alpha;

   typedef float _omega_type;
  _omega_type omega;

   typedef float _gamma_type;
  _gamma_type gamma;





  typedef boost::shared_ptr< ::robot2::Reperage_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot2::Reperage_<ContainerAllocator> const> ConstPtr;

}; // struct Reperage_

typedef ::robot2::Reperage_<std::allocator<void> > Reperage;

typedef boost::shared_ptr< ::robot2::Reperage > ReperagePtr;
typedef boost::shared_ptr< ::robot2::Reperage const> ReperageConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot2::Reperage_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot2::Reperage_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robot2

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'robot2': ['/home/florian/catkin_workspace/src/robot2/msg', '/home/florian/catkin_workspace/src/robot2/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robot2::Reperage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot2::Reperage_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot2::Reperage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot2::Reperage_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot2::Reperage_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot2::Reperage_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot2::Reperage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "edee403981ddd7ed65182c1f936a872a";
  }

  static const char* value(const ::robot2::Reperage_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xedee403981ddd7edULL;
  static const uint64_t static_value2 = 0x65182c1f936a872aULL;
};

template<class ContainerAllocator>
struct DataType< ::robot2::Reperage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot2/Reperage";
  }

  static const char* value(const ::robot2::Reperage_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot2::Reperage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 alpha\n\
float32 omega\n\
float32 gamma\n\
";
  }

  static const char* value(const ::robot2::Reperage_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot2::Reperage_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.alpha);
      stream.next(m.omega);
      stream.next(m.gamma);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Reperage_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot2::Reperage_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot2::Reperage_<ContainerAllocator>& v)
  {
    s << indent << "alpha: ";
    Printer<float>::stream(s, indent + "  ", v.alpha);
    s << indent << "omega: ";
    Printer<float>::stream(s, indent + "  ", v.omega);
    s << indent << "gamma: ";
    Printer<float>::stream(s, indent + "  ", v.gamma);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT2_MESSAGE_REPERAGE_H
